apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: flavito
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: flavito 
  name: flavito
  namespace: rhtap
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: flavito 
